server:
  port: 0

info:
  component: Forecast Micro service - UP 

eureka:
  instance:
    hostName: localhost
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 
    registryFetchIntervalSeconds: 5
